name: dart_frog_dependency_cacher
description: An opinionated caching and dependency injection suite for Dart Frog.
version: 0.0.3
repository: https://github.com/Morel-Tech/dart_frog_dependency_cacher

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
